config/routes.rb
Table::Application.routes.draw do
  resources :transactions
  resources :users

  root :to => 'users#index'
  get 'users/:user_id/event' => 'users#event_new'
  post 'users/:user_id/event' => 'users#event_create'

  get 'auth' => 'users#login'
  post 'auth' => 'users#auth'
  get 'close' => 'users#logout'

  

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit]#, :update, :destroy]
  before_filter :authorize, only: [:index, :show, :new, :edit, :create]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.order('created_at DESC').page(params[:page])
    @users = User.order('balance DESC')
    @sum_of_balances = User.sum_of_balances
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  # def update
  #   respond_to do |format|
  #     if @transaction.update(transaction_params)
  #       format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: 'edit' }
  #       format.json { render json: @transaction.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  # def destroy
  #   @transaction.destroy
  #   respond_to do |format|
  #     format.html { redirect_to transactions_url }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:from_user_id, :to_user_id, :amount, :description)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_user_id %><br>
    <%= f.number_field :from_user_id %>
  </div>
  <div class="field">
    <%= f.label :to_user_id %><br>
    <%= f.number_field :to_user_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h3>거래내역</h3>
<br />
<a href="/users" class="btn btn-warning">돌아가기</a>
<br /><br />
<% @users.each do |user| %>
  <% unless user.is_removed %>
    <div>
      <%= user.name %> <%= number_with_delimiter(user.balance) %>원
    </div>
    <div class="progress" style="margin-bottom: 5px">
      <% if user.bar_percent >= 0 %>
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <%= user.bar_percent %>%">
        </div>
      <% else %>
        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <%= -user.bar_percent %>%">
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<p style="color: #989898">오차 <%= number_with_delimiter(@sum_of_balances) %>원</p>
<br /><br />
<%= paginate @transactions, :remote => false %>
<% @transactions.each do |transaction| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <% if transaction.amount >= 0 %>
        <%= transaction.from_user.name %> <span class="glyphicon glyphicon-arrow-right"></span> <%= transaction.to_user.name %> <br />
        <%= number_with_delimiter(transaction.amount) %>원<br />
      <% else %>
        <%= transaction.to_user.name %> <span class="glyphicon glyphicon-arrow-right"></span> <%= transaction.from_user.name %> <br />
        <%= number_with_delimiter(-transaction.amount) %>원<br />
      <% end %>
      <% if transaction.description.to_s.length > 0 %>
        <%= transaction.description %><br />
      <% end %>
      <%= transaction.created_at.in_time_zone('Seoul') %><br />
      (<%= time_ago_in_words(transaction.created_at) %> ago)
    </div>
  </div>
  <!--td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
<% end %>
<%= paginate @transactions, :remote => false %>
<br />

<!--%= link_to 'New Transaction', new_transaction_path %-->
<a href="/users" class="btn btn-warning">돌아가기</a>
<br /><br />&nbsp;

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From user:</strong>
  <%= @transaction.from_user_id %>
</p>

<p>
  <strong>To user:</strong>
  <%= @transaction.to_user_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>